name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit and integration tests
        run: |
          python -m unittest discover -s tests
      - name: Run REST API tests
        run: |
          python -m unittest tests/test_rest_api.py
      - name: Upload logs if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            app.log
            agent/agent.log
            central_server/server.log 